// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { PrismaClient } from '../generated/prisma/client.ts'
import { PrismaBetterSqlite3 } from '@prisma/adapter-better-sqlite3'
import { env } from './env.js'

const adapter = new PrismaBetterSqlite3({
  url: env.DATABASE_URL,
})

const prisma = new PrismaClient({ adapter })

export default prisma

